# Generated by Django 5.0.6 on 2024-06-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0002_email_msg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='from_email',
            field=models.CharField(max_length=255),
        ),
    ]
