# Generated by Django 5.0.6 on 2024-06-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0003_alter_email_from_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='msg_id',
            field=models.CharField(max_length=20),
        ),
    ]
