# Generated by Django 5.0.6 on 2024-06-16 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0004_alter_email_msg_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
    ]
